### ISSUE TITLE
undefined symbol: OPENSSL_cleanup

### ISSUE THREAD

**Issue by toralf** [processone/fast_tls#13]
I run into this run-time error under a Gentoo Linux with libressl.
All details are in https://bugs.gentoo.org/show_bug.cgi?id=603368 

Tested 1.0.7 too - same issue, 1.0.3 works fine

**Comment by prefiks** [comment]
Hi, this will be fixed by version 1.0.9 that i just prepared,

**Comment by toralf** [comment]
cool :-)
and works fine - tested a sec ago
