### ISSUE TITLE
failed to load TLS driver

### ISSUE THREAD

**Issue by zhangcunxiang** [processone/fast_tls#3]
when I use the lib into my ejabberd project ,at the point of start fast_tls application crashed
CRASH REPORT is : 
**{shutdown,
                         {failed_to_start_child,fast_tls,{open_error,-10}}},
                     {fast_tls_app,start,[normal,[]]}**
and got the error :
**[error] failed to load TLS driver: cannot open shared object file: No such file or directory**

**Comment by mremond** [comment]
Error seems self explanatory: "No such file or directory".
Likely, it means you have incorrectly build the system.

**Comment by zhangcunxiang** [comment]
I find fast_tls_drv.so file is just lay in $prefix/lib/ejabberd/priv/lib directory
with to many failure trys I roll back to p1_tls and p1_sip and make && make install 
the error is gone

**Comment by mremond** [comment]
We fixed a different error:

```
failed to load TLS driver: dlopen(/build/ejabberd/deps/fast_tls/priv/lib/fast_tls_drv.so, 2): Symbol not found: _erl_exit
```

But it may help with your issue.

**Comment by zhangcunxiang** [comment]
@mremond I think the error you fixed is the same one as we came across :
`failed to load TLS driver: dlopen(/appl/src/ejabberd14/lib/ejabberd/priv/lib/fast_tls_drv.so, 2): Symbol not found: _erl_exit`
can you tell me how did you fixed the error.
thank you in advance , and appreciate for your contribution of ejabberd such a very nice open source application.
