### ISSUE TITLE
publish 1.0.17 to hex.pm

### ISSUE THREAD

**Issue by facundoolano** [processone/fast_tls#30]
Hi, I'm using processone/stun, which depends on this driver. Since stun uses a legacy dependency format, rebar3 will try to fetch it from hex.pm instead of directly from git:

```
===> Package fast_tls-1.0.17 not found. Fetching registry updates and trying again...
===> Updating package registry...
===> Writing registry to /Users/facundo/.cache/rebar3/hex/default/registry
===> Generating package index...
===> Writing index to /Users/facundo/.cache/rebar3/hex/default/packages.idx
===> Package not found in registry: fast_tls-1.0.17.
```

This doesn't happen with previous versions of processone/stun that depend on fast_tls-1.0.16 (which is published). So that error would go away by publishing 1.0.17 to hex.pm.

(I can file this issue in the stun repo if you feel it belongs there).

Thanks!

**Comment by cromain** [comment]
1.0.18 was published
