### ISSUE TITLE
FTBFS with OpenSSL 1.1.1

### ISSUE THREAD

**Issue by debalance** [processone/fast_tls#36]
According to https://bugs.debian.org/907055 the transmission test fails when building fast_tls with OpenSSL 1.1.1.
Whatever it is, please either fix the test or fast_tls (or both).

**Comment by prefiks** [comment]
Hello,

As of d8c5a714d15b7ab2615e548d214d3eb7670c718b this should be fixed. At least tests passes with libssl1.1.1~pre9 from debian unstable.
