### ISSUE TITLE
erlang:system_info(version) check is wrong

### ISSUE THREAD

**Issue by darix** [processone/fast_tls#4]
```
Erlang/OTP 18 [erts-7.0.3] [source] [64-bit] [smp:4:4] [async-threads:10] [hipe] [kernel-poll:false]

Eshell V7.0.3  (abort with ^G)
1> erlang:system_info(version).
"7.0.3"
```

this leads to

```
list_to_float("7.0.3")
```

this was broken in https://github.com/processone/fast_tls/commit/3efd01546d6866acdf130b4d2cbe349978663883

**Comment by darix** [comment]
Probably something for @prefiks

**Comment by darix** [comment]
1. you leave a 2nd closing ) in that line
2. I asked my local erlang expert ... while ">=" works with strings "7.10" >= "7.9" would give you a false.

**Comment by prefiks** [comment]
Problem with extra ) was already fixed, but i also now pushed change that improved parsing version string
