### ISSUE TITLE
Can I use "port level lock" for fast_tls_drv?

### ISSUE THREAD

**Issue by taiyow** [processone/fast_tls#5]
I use fast_tls and ejabberd with very large number of processes, and in this case fast_tls_drv can be bottleneck with default "driver level lock".
I changed fast_tls_drv.c to use "port level lock" and then connection throughput was increased without any confusion of connection.

So my question is: does fast_tls support port level lock ?

I read fast_tls_drv.c, and found only one global variable `ssl_index` which is modified only in DRIVER_INIT function, so I think this answer is yes.

**Comment by prefiks** [comment]
We switched this module to use nif so this no longer apply
