### ISSUE TITLE
FTBFS with openssl 1.1.0

### ISSUE THREAD

**Issue by debalance** [processone/fast_tls#6]
Hi,

fast_tls fails to build with with OpenSSL 1.1.0 which is about to be released.

You can find more information here: https://bugs.debian.org/828297

**Comment by prefiks** [comment]
This should be fixed by commit 3d09f86171e455c8ee8b64a5b33f1f28022b7f2d

**Comment by debalance** [comment]
Thx for fixing it so quickly! This solves the FTBFS issue for me, but rebar eunit segfaults:

> root@emmagan:/tmp/buildd/erlang-p1-tls-1.0.4# rebar eunit
> ==> erlang-p1-tls-1.0.4 (eunit)
>   All 8 tests passed.
> Cover analysis: /build/erlang-p1-tls-1.0.4/.eunit/index.html
> Coverdata export: /build/erlang-p1-tls-1.0.4/.eunit/cover.coverdata
> Segmentation fault

However that probably happens because erlang itself or some other library hasn't been rebuilt with the new libssl yet. With libssl1.0.2 I don't have that problem.

**Comment by prefiks** [comment]
Ok, i see that SIGSEGV too with 1.1.0, will see if i will be able to see what causes that.

**Comment by prefiks** [comment]
This segfault should be fixed in latest version, looks like openssl do now call cleanup function when library is unregistered, and this tried to call callbacks from p1_tls_drv.so but those were no longer available at that point, i made it call cleanup code earlier, so we no longer try to do that.

**Comment by debalance** [comment]
I can confirm the segfault is gone :)
