### ISSUE TITLE
:fast_tls fails to start - Failed to load NIF library

### ISSUE THREAD

**Issue by econnolly** [processone/fast_tls#7]
I'm using Elixir 1.3.0, fast_tls from hex.pm (current version is 1.0.5)
On OSX El Capitan 10.11.5

Create a new mix app. Add the fast_tls dependency and application to mix.exs:

```
def application do
  [applications: [:logger, :fast_tls]]
end

defp deps do
  [{:fast_tls, "~> 1.0"}]
end
```

Then run:
$ mix deps.get

I get the following output from the compile command:

===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"2.5.1">>})
===> Downloaded package, caching at /Users/edward/.cache/rebar3/hex/default/packages/rebar3_hex-2.5.1.tar
===> Compiling rebar3_hex
===> Compiling p1_utils
===> Fetching rebar3_hex ({pkg,<<"rebar3_hex">>,<<"2.5.1">>})
===> Downloaded package, caching at /Users/edward/.cache/rebar3/hex/default/packages/rebar3_hex-2.5.1.tar
===> Compiling rebar3_hex
===> Compiling fast_tls

Then run:
$ mix

But the application will not start:

*\* (Mix) Could not start application fast_tls: exited in: :fast_tls_app.start(:normal, [])
    *\* (EXIT) an exception was raised:
        *\* (MatchError) no match of right hand side value: {:error, {:load_failed, 'Failed to load NIF library: \'dlopen(/Users/edward/Development/tls_test
/_build/dev/lib/fast_tls/priv/lib/p1_sha.so, 2): image not found\''}}
            (fast_tls) /Users/edward/Development/tls_test/deps/fast_tls/src/fast_tls_app.erl:53: :fast_tls_app.start/2
            (kernel) application_master.erl:273: :application_master.start_it_old/4

**Comment by econnolly** [comment]
Getting this on fast_xml too.  Might not be an issue with this project.

**Comment by NZSmartie** [comment]
### Just a heads up

[fast_yaml](https://github.com/processone/fast_yaml) has this issue as well. There's an open [pull request](https://github.com/processone/fast_yaml/pull/4) to add support for rebar3. When manually patching the same files in both [fast_xml](https://github.com/processone/fast_xml) and [fast_tls](https://github.com/processone/fast_tls), they both compile fine and the error is resolved.

**Comment by edwardconnolly** [comment]
Thank you for taking the time to post this - I applied the patch and it's working once more.

**Comment by econnolly** [comment]
Thank you for taking the time to post this - I applied the patch and it's working once more.

**Comment by cromain** [comment]
this was fixed long time ago
